name: ftest
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_inappwebview: ^6.1.5
  flutter_html: ^3.0.0
  path_provider: ^2.1.1
  usb_serial: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/index.html
    - assets/script.js
    - assets/style.css
    - assets/register.html
    - assets/register.js
    - assets/register.css
